### ISSUE TITLE
Event.body is an object

### ISSUE THREAD

**Issue by bduff9** [vendia/serverless-express#259]
I had a working lambda that handles basic get requests.  I had to implement the webpack serverless plugin recently for another issue, and now when a request is made, I get the following error:
```
2019-11-05T16:15:11.032Z 0055b8bf-3549-4acd-83b1-357c731b3803 INFO ERROR: aws-serverless-express error
2019-11-05T16:15:11.033Z 0055b8bf-3549-4acd-83b1-357c731b3803 ERROR TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
at Function.from (buffer.js:232:9)
at getEventBody (/var/task/node_modules/aws-serverless-express/src/index.js:25:17)
at mapApiGatewayEventToHttpRequest (/var/task/node_modules/aws-serverless-express/src/index.js:46:18)
at forwardRequestToNodeServer (/var/task/node_modules/aws-serverless-express/src/index.js:135:28)
at proxy (/var/task/node_modules/aws-serverless-express/src/index.js:202:7)
at Server.startServer.on (/var/task/node_modules/aws-serverless-express/src/index.js:206:32)
at Server.emit (events.js:203:15)
at Server.EventEmitter.emit (domain.js:448:20)
at emitListeningNT (net.js:1314:10)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

I found the line added to aws-serverless-express that check for event.body and then uses it to set content-length, which is causing this issue as for some reason my event.body === `{}` now.

This did work prior to adding the serverless-webpack plugin, so unsure exactly what is going on however I did read the comments on that content-length PR, and one assumption was that event.body would always be a string so not totally sure what to do here.  Any help would be appreciated.

EDIT: If I manually change the empty object in event.body to an empty string `''` then I get a different error regarding requestPath:
```
2019-11-05T17:38:48.956Z 15280953-68b6-4797-9204-ed0bc36910f6 INFO ERROR: aws-serverless-express error
2019-11-05T17:38:48.957Z 15280953-68b6-4797-9204-ed0bc36910f6 ERROR TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
at new ClientRequest (_http_client.js:115:13)
at Object.request (http.js:42:10)
at forwardRequestToNodeServer (/var/task/node_modules/aws-serverless-express/src/index.js:136:22)
at proxy (/var/task/node_modules/aws-serverless-express/src/index.js:202:7)
at Server.startServer.on (/var/task/node_modules/aws-serverless-express/src/index.js:206:32)
at Server.emit (events.js:203:15)
at Server.EventEmitter.emit (domain.js:448:20)
at emitListeningNT (net.js:1314:10)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

After seeing this and being unable to fix, I went back and ripped out the webpack plugin to go back to the typescript plugin.  Unfortunately, still get the same errors as above with that plugin as well.  No idea what else has changed since it was working right before initially adding the webpack plugin.

**Comment by selvarajblr93** [comment]
I am facing a similar issue, do anyone has a solution for this, In my organization, we are using our own API Gateway setup which triggers ALB Lambda API, when I call ALB directly using postman, everything works fine, but when I call via using the API Gateway(which trigger ALB). I am getting the below error.


instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at Function.from (buffer.js:331:9)
    at getEventBody (/var/task/node_modules/aws-serverless-express/src/index.js:25:17)
    at mapApiGatewayEventToHttpRequest (/var/task/node_modules/aws-serverless-express/src/index.js:46:18)
    at forwardRequestToNodeServer (/var/task/node_modules/aws-serverless-express/src/index.js:135:28)
    at Object.proxy (/var/task/node_modules/aws-serverless-express/src/index.js:202:7)
    at Runtime.exports.handler (/var/task/index.js:24:26)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by joain946** [comment]
I'm experiencing this issue as well.
When using Nest.js api:s using either "mystream.pipe(res)" for binary content or if I'm just returning a "string" then the Body response always becomes an empty object ("{}").
When I return a normal object then I get the full Json back, just as expected.

Example of a binary stream response:
`HTTP/1.1 200 OK
Date: Mon, 09 Nov 2020 15:42:19 GMT
Content-Type: application/octet-stream; charset=utf-8
Content-Length: 2
Connection: keep-alive
X-Powered-By: Express
etag: W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8"
Apigw-Requestid: Vvx1ZiKQIAMEJRg=

{}`

**Comment by AlessandroAnnini** [comment]
@brettstack  can we please reopen this one?
