### ISSUE TITLE
Integration test fails

### ISSUE THREAD

**Issue by kennyhyun** [vendia/serverless-express#305]
I just ran `npm i && npm test` and get this on the master branch.

`node -v`:  v12.18.0
`npm -v` : 6.14.4

```
yarn run v1.22.4
$ jest
 FAIL  __tests__/integration.js
  ● Test suite failed to run

    Cannot find module 'express' from 'app.js'

    However, Jest was able to find:
        '../examples/basic-starter/app.js'
        '../examples/basic-starter/app.local.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      1 | 'use strict'
      2 | const path = require('path')
    > 3 | const express = require('express')
        |                 ^
      4 | const bodyParser = require('body-parser')
      5 | const cors = require('cors')
      6 | const compression = require('compression')

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (examples/basic-starter/app.js:3:17)

```

after I added packages by `npm i -D express cors compression`, it yields more errors

such as

```
 FAIL  __tests__/integration.js
  ● Console

    console.log src/index.js:122
      ERROR: aws-serverless-express error
    console.error src/index.js:123
      TypeError: Cannot read property 'headers' of null
          at mapApiGatewayEventToHttpRequest (/home/kenny/Projects/github/aws-serverless-express/src/index.js:42:43)
          at forwardRequestToNodeServer (/home/kenny/Projects/github/aws-serverless-express/src/index.js:135:28)
          at Object.proxy (/home/kenny/Projects/github/aws-serverless-express/src/index.js:202:7)
          at Object.<anonymous> (/home/kenny/Projects/github/aws-serverless-express/__tests__/integration.js:426:26)
          at /home/kenny/Projects/github/aws-serverless-express/node_modules/jest-jasmine2/build/queueRunner.js:43:12
          at new Promise (<anonymous>)
          at mapper (/home/kenny/Projects/github/aws-serverless-express/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
          at /home/kenny/Projects/github/aws-serverless-express/node_modules/jest-jasmine2/build/queueRunner.js:73:41
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
    console.warn src/index.js:185
      WARNING: Attempting to listen on socket /tmp/server-fo4bhbu5mla.sock, but it is already in use. This is likely as a result of a previous invocation error or timeout. Check the log
s for the invocation(s) immediately prior to this for root cause, and consider increasing the timeout and/or cpu/memory allocation if this is purely as a result of a timeout. aws-server
less-express will restart the Node.js server listening on a new port and continue with this request.
```

I am not sure this project is actually maintained.

**Comment by brettstack** [comment]
Fixed in v4
